#please provide the name of the workflow
name: String To Base 64 Encode Workflow

#Provide the trigger on the workflow call and also provide the inputs & outputs of this workflow
on: 
  push:
    branches:
      - "feature1"

jobs:

#This job performs the bas64 encoding of the input value
   Encoding_String_To_Base64:
    uses: tusharmathur08/officialworkflows/.github/workflows/base64.yaml@feature1
    with:
      string_value: "test"
     
   Display_encoded_value:
     runs-on: ubuntu-latest
     needs: Encoding_String_To_Base64
     steps:

       - name: Display encoded value
         run: echo ${{needs.Encoding_String_To_Base64.outputs.base64_encoded_value}}